version: '3.4'

services:
  event-database:
    container_name: EventDatabase
    environment:
      - POSTGRES_DB=EventDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.containers/db:/var/lib/postgresql/data

  eventmanagement.events.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=event-database;Port=5432;Database=EventDatabase;UserId=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "5000:8080"
      - "5050:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro