version: '3.4'

services:

  event.database:
    image: postgres:latest
  
  eventmanagement.seq:
    image: datalust/seq:latest

  pgadmin:
    image: dpage/pgadmin4

  eventmanagement.redis:
    image: redis:latest
    

  eventmanagement.api:
    image: ${DOCKER_REGISTRY-}eventmanagementapi
    build:
      context: ..
      dockerfile: EventManagement/src/Apis/EventManagement.Api/Dockerfile

