version: '3.4'

services:
  event.database:
    container_name: EventManagementDatabase
    environment:
      - POSTGRES_DB=EventManagementDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.containers/db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4.container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 4040:80
      
 
  eventmanagement.seq:
    container_name: EventManagement.Seq
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80  

  eventmanagement.redis:
    container_name: EventManagement.Redis
    restart: always
    ports:
      - 6379:6379
  eventmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Databse=Host=event.database;Port=5432;Database=EventManagementDatabase;UserId=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Cache=eventmanagement.redis:6379
    ports:
      - "5000:8080"
      - "5050:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
